import { useEffect, useState } from "react";
import Header from "./Header";
import Footer from "./Footer";
import SideBar from "./SideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return <></>;
  }

  return (
    <>
      <Header />
      <SideBar />
      <main className="w-full min-h-screen pl-220px pt-60px">{children}</main>
      {/* <Footer /> */}
    </>
  );
};

export default RootLayout;
